create table articles (
pmid string,
pmc string,
doi string,
other_id string,
title string,
abstract string,
authors string,
mesh_terms string,
publication_types string,
keywords string,
chemical_list string,
pubdate string,
pubyear int,
journal string,
medline_ta string,
nlm_unique_id string,
issn_linking string,
country string,
reference string,
deleteflag boolean
);